# Generated by Django 4.0.1 on 2022-01-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GitRepoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_created_date", models.DateField(auto_now_add=True)),
                ("row_updated_date", models.DateField(auto_now=True)),
                ("source", models.CharField(max_length=255)),
                ("owner", models.CharField(max_length=255)),
                ("repo", models.CharField(max_length=255)),
                ("days_since_update", models.IntegerField()),
                ("days_since_create", models.IntegerField()),
                ("watchers", models.IntegerField()),
                ("pull_requests_open", models.IntegerField()),
                ("pull_requests_total", models.IntegerField()),
                ("has_issues", models.BooleanField()),
                ("open_issues", models.IntegerField()),
                ("commits_total", models.IntegerField()),
                ("commits_recent", models.IntegerField()),
                ("branch_count", models.IntegerField()),
                ("authors_total", models.IntegerField()),
                ("authors_recent", models.IntegerField()),
                ("lines_of_code_total", models.IntegerField()),
                ("files_total", models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="gitrepodata",
            constraint=models.UniqueConstraint(
                fields=("source", "owner", "repo"), name="unique_repo"
            ),
        ),
    ]
