# Generated by Django 4.0.1 on 2022-01-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitrepodata",
            name="days_since_commit",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
