# Generated by Django 4.0.1 on 2022-01-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0002_gitrepodata_days_since_commit"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitrepodata",
            name="prolific_author_commits_recent",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gitrepodata",
            name="prolific_author_commits_total",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
