# Generated by Django 4.0.2 on 2022-02-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0003_gitrepodata_prolific_author_commits_recent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitrepodata",
            name="commit_interval_all_mean",
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gitrepodata",
            name="commit_interval_all_stdev",
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gitrepodata",
            name="commit_interval_recent_mean",
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gitrepodata",
            name="commit_interval_recent_stdev",
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gitrepodata",
            name="version",
            field=models.CharField(default="0.0.0", max_length=32),
            preserve_default=False,
        ),
    ]
