# Generated by Django 4.0.2 on 2022-02-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0004_gitrepodata_commit_interval_all_mean_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CacheData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_created_date", models.DateField(auto_now_add=True)),
                ("row_updated_date", models.DateField(auto_now=True)),
                ("version", models.CharField(max_length=32)),
                ("source", models.CharField(max_length=255)),
                ("owner", models.CharField(max_length=255)),
                ("repo", models.CharField(max_length=255)),
                ("code_lines_of_code", models.IntegerField()),
                ("code_file_count", models.IntegerField()),
                ("pull_request_count", models.IntegerField()),
                ("pull_request_count_open", models.IntegerField()),
                ("commit_all_count", models.IntegerField()),
                ("commit_all_count_primary_author", models.IntegerField()),
                ("commit_all_interval_mean", models.FloatField()),
                ("commit_all_interval_standard_deviation", models.FloatField()),
                ("commit_recent_count", models.IntegerField()),
                ("commit_recent_count_primary_author", models.IntegerField()),
                ("commit_recent_interval_mean", models.FloatField()),
                ("commit_recent_interval_standard_deviation", models.FloatField()),
                ("contributor_days_since_create", models.IntegerField()),
                ("contributor_days_since_commit", models.IntegerField()),
                ("contributor_branch_count", models.IntegerField()),
                ("contributor_author_count_all", models.IntegerField()),
                ("contributor_author_count_recent", models.IntegerField()),
                ("popularity_watcher_count", models.IntegerField()),
                ("popularity_has_issues", models.BooleanField()),
                ("popularity_open_issue_count", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="GitRepoData",
        ),
        migrations.AddConstraint(
            model_name="cachedata",
            constraint=models.UniqueConstraint(fields=("source", "owner", "repo"), name="unique_repo"),
        ),
    ]
