# Generated by Django 4.0.2 on 2022-03-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0005_cachedata_delete_gitrepodata_cachedata_unique_repo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cachedata",
            name="code_file_count",
        ),
        migrations.RemoveField(
            model_name="cachedata",
            name="code_lines_of_code",
        ),
        migrations.RemoveField(
            model_name="cachedata",
            name="commit_all_count",
        ),
        migrations.RemoveField(
            model_name="cachedata",
            name="commit_all_count_primary_author",
        ),
        migrations.RemoveField(
            model_name="cachedata",
            name="commit_all_interval_mean",
        ),
        migrations.RemoveField(
            model_name="cachedata",
            name="commit_all_interval_standard_deviation",
        ),
        migrations.RemoveField(
            model_name="cachedata",
            name="contributor_author_count_all",
        ),
    ]
