# Generated by Django 4.0.3 on 2022-03-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0006_remove_cachedata_code_file_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cachedata",
            name="contributor_branch_count",
        ),
        migrations.RemoveField(
            model_name="cachedata",
            name="popularity_has_issues",
        ),
    ]
